apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javi-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/javi-jmnz/argocd
    path: k8s # ðŸ‘ˆ OJO: aquÃ­ usa tu nueva carpeta
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true # borra recursos que ya no existen en Git
      selfHeal: true # repara drift del cluster
    syncOptions:
      - CreateNamespace=true
